### ISSUE TITLE
[1pt] Determine if Anechoic is needed or not

### ISSUE THREAD

**Issue by scasplte2** [Topl/AnechoicBifrostProvider#1]
@jingsting when you get the chance, please spin up this project and let me know what is going on here. It appears that Alex split out networking into it's own repo. I think he did this so he could play with different peer management schemes but I am not sure.

There is also this paper doc with the same name
https://paper.dropbox.com/doc/Anechoic--Av5ngC3dj3~L~~uxIuyIuxbhAg-viHQk9HmoUyUM0XZK2EEm

**Comment by scasplte2** [comment]
@jingsting what were the result of spinning this up? Is it useful at all as a testing ground for the Akka based network controllers or can I just delete the repository completely because it is redundant/not useful/not documented?

Please provide some sort of link to work done or conclusions drawn in the issue itself before closing the ticket.

**Comment by jingsting** [comment]
Nick and I went and took a look at it last week. The project is not finished with some networking parts left to implement. I don't think we need the repo anymore. Sorry I forgot to comment on this
